# docker-compose.yml
version: '3.9'
services:
  db2:
    image: postgres:15
    environment:
      POSTGRES_USER: raffle
      POSTGRES_PASSWORD: rafflepass
      POSTGRES_DB: raffle_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raffle"]
      interval: 5s
      retries: 5


  rabbitmq1:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  api:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      db2:
        condition: service_healthy
      rabbitmq1:
        condition: service_started

